"use-client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import Navigation from "@/components/navigation";

import logo from "public/logo.png";

const inter = Inter({ subsets: ["latin"] });
const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      // suppressHydrationWarning
      lang="en"
    >
      <body
        className={`${inter.className} static bg-gray-100 ${fontSans.variable}`}
      >
        <Navigation />
        <main className="h-screen overflow-scroll">{children}</main>
        <footer className="fixed w-full bottom-0 flex h-20 justify-between items-center">
          <div className="m-4">Google</div>
          <div className="m-4">Appelez-nous au 01 XX XX XX XX</div>
        </footer>
      </body>
    </html>
  );
}
